---
title: "Assignment3"
output:
  html_document: default
---

## **Load Libraries**
```{r}

library(class)
library(caret)
library(gmodels)
library(readr)
library(reshape2)
library(e1071)

```
<br>

## **Import Data**
```{r}

UniversalBank <- read_csv("UniversalBank.csv")

```
*Data sourced from Canvas.*

<br>

## **Split Data**
```{r}

set.seed(123)
Index_Train <- createDataPartition(UniversalBank$`Personal Loan`, p=0.6, list = F)
Train <- UniversalBank[Index_Train,]
Valid <- UniversalBank[-Index_Train,]

```
<br>

## **Training Pivot Table**
```{r}

Train_Melt <- melt(Train, id.vars = c("CreditCard", "Online", "Personal Loan"))
Pivot_Table <- dcast(Train_Melt, CreditCard + `Personal Loan` ~ Online, fun.aggregate = length)
print(Pivot_Table)

```
<br>

## **Probability**

$P(Loan = 1|CreditCard = 1, Online = 1)$
```{r}

Prob_Online <- (Pivot_Table[4,4] / (Pivot_Table[3,4] + Pivot_Table[4,4]))
print(Prob_Online)
print(paste("If a customer who owns a bank credit card and is actively using online banking services.",
            "The probability that this customer will accept the loan offer is", Prob_Online * 100, "%"))

```
<br>
