---
title: "Assignment5"
output: html_document
---

## **Load Libraries**
```{r}

library(readr)
library(cluster)
library(stats)
library(dplyr)
library(caret)
library(tidyverse)
library(factoextra)

```
<br>

## **Import Data**
```{r}

Cereals <- read_csv("Cereals.csv")

```
*Data sourced from Canvas.*

<br>

## **Turn Names Into Row Names**
```{r}

head(Cereals)
Cereals_df <- as.data.frame(Cereals)
Cereal_Names <- Cereals_df$name
rownames(Cereals_df) <- Cereal_Names
Cereals_df <- Cereals_df[,-1]
head(Cereals_df)

```
<br>

## **Remove Missing Values**
```{r}

colMeans(is.na(Cereals_df))
sum(!complete.cases(Cereals_df))
Cereals_Clean <- Cereals_df[complete.cases(Cereals_df), ]
colMeans(is.na(Cereals_Clean))

```
<br>

## **Create Dummy Variables**
```{r}

head(Cereals_Clean)
Dummies <- dummyVars(~ mfr + type, data = Cereals_Clean)
Dummy_df <- as.data.frame(predict(Dummies, newdata = Cereals_Clean))
Cereals_Num <- Cereals_Clean[,-c(1,2)]
Cereals_Num <- cbind(Dummy_df,Cereals_Num)
head(Cereals_Num)

```
<br>

## **Normalize Data**
```{r}

Norm_Model <- preProcess(Cereals_Num, method = c("center", "scale"))
Cereals_Norm <- predict(Norm_Model,Cereals_Num)
head(Cereals_Norm)

```
<br>

## **Agnes Linkage Methods**
```{r}

hc_single <- agnes(Cereals_Norm, method = "single")
hc_complete <- agnes(Cereals_Norm, method = "complete")
hc_average <- agnes(Cereals_Norm, method = "average")
hc_ward <- agnes(Cereals_Norm, method = "ward")

Methods <- data.frame(Single = hc_single$ac, Complete = hc_complete$ac,
                      Average = hc_average$ac, Ward = hc_ward$ac)
Methods
max(Methods)
names(which.max(Methods))

```
<br>

## **Agnes Dendrogram**
```{r}

pltree(hc_ward, cex = 0.6, hang = -1, main = "Dendrogram of Agnes")

```
<br>

## **Choosing Number of Clusters**
```{r}

fviz_nbclust(Cereals_Norm, hcut, method = "wss") +
  geom_hline(yintercept = 1194, linetype = 2, color = "royalblue", size = 0.5)

```
<br>

## **3 Clusters Dendrogram**
```{r}

pltree(hc_ward, cex = 0.6, hang = -1, main = "Dendrogram of Agnes")
rect.hclust(as.hclust(hc_ward), k = 3, border = 2:5)

```
<br>

## **Stability Check**
```{r}

set.seed(124) # seed(123) is unbalanced
Index_Partition <- createDataPartition(1:nrow(Cereals_Norm), p = 0.7, list = F)
PartA <- Cereals_Norm[Index_Partition,]
PartB <- Cereals_Norm[-Index_Partition,]

Clusters_Ward <- cutree(as.hclust(hc_ward), k = 3)
Clusters_B <- Clusters_Ward[-Index_Partition]

hc_A <- agnes(PartA, method = "ward")
Clusters_A <- cutree(as.hclust(hc_A), k = 3)


Centroids <- PartA %>%
  mutate(Cluster = Clusters_A) %>%
  group_by(Cluster) %>%
  summarise(across(everything(), mean))
Centroids

Centroid_1 <- Centroids[1,-1]
Centroid_2 <- Centroids[2,-1]
Centroid_3 <- Centroids[3,-1]

Cent_Dist_1 <- sqrt(rowSums((PartB - as.list(Centroid_1))^2))
Cent_Dist_2 <- sqrt(rowSums((PartB - as.list(Centroid_2))^2))
Cent_Dist_3 <- sqrt(rowSums((PartB - as.list(Centroid_3))^2))

Centroid_Distances <- data.frame(
  Dist1 = Cent_Dist_1,
  Dist2 = Cent_Dist_2,
  Dist3 = Cent_Dist_3
)

Centroid_Distances$Assigned_Cluster <- max.col(-1*Centroid_Distances)
Centroid_Distances$HC_Cluster <- Clusters_B
Centroid_Distances

Assigned <- factor(Centroid_Distances$Assigned_Cluster)
HC <- factor(Centroid_Distances$HC_Cluster)
ConfMatrix <- confusionMatrix(Assigned, HC)
ConfMatrix$table
ConfMatrix$overall[1]

```
<br>

## **Cluster Selection**
```{r}

pltree(hc_ward, cex = 0.6, hang = -1, main = "Dendrogram of Agnes")
rect.hclust(as.hclust(hc_ward), k = 3, border = c("red","white","white"))
Healthy_Cluster <- Cereals_Norm[Clusters_Ward == 1, ]
HC_Healthy_Cluster <- agnes(Healthy_Cluster, method = "ward")
pltree(HC_Healthy_Cluster, cex = 0.6, hang = -1, main = "Dendrogram of Healthy Cereals")
row.names(Healthy_Cluster)

```
<br>
