---
title: "Assignment1"
output: html_document
---

## Load Libraries
```{r}

library(dplyr)
library(ggplot2)
library(readr)

```

## Import Data
```{r}

Cereals <- read_csv("Cereals.csv")

```
## Descriptive Statistics

### Quantitative Variables
```{r}

Cereals %>%
  select(calories, protein, fat, sodium, fiber, carbo, sugars, potass, vitamins, weight, cups, rating) %>%
  summary()

```
### Qualitative Variables
#### Manufacturer:
*A = American Home Food Products; G = General Mills; K = Kelloggs; N = Nabisco; P = Post; Q = Quaker Oats; R = Ralston Purina*
```{r}

table(Cereals$mfr)

```
#### Type:
*C = Cold; H = Hot*
```{r}

table(Cereals$type)

```
#### Display Shelf:
*1, 2, or 3, counting from the floor*
```{r}

table(Cereals$shelf)

```

## Transforming a Variable
#### Turning type into a binary:
```{r}

# Before Transform
print(Cereals)
Cereals <- Cereals %>%
  mutate(is_cold = type == "C") %>%
  select(name, mfr, is_cold, everything(), -type)

table(Cereals$is_cold)
# After Transform
print(Cereals)

```
