---
title: "Assignment2"
output: html_document
---

## **Load Libraries**
```{r}

library(class)
library(caret)
library(gmodels)
library(readr)

```
<br>

## **Import Data**
```{r}

UniversalBank <- read_csv("UniversalBank.csv")

```
*Data sourced from Canvas.*

<br>

## **Drop Data**
```{r}

UniversalBank <- UniversalBank[,-5]
UniversalBank <- UniversalBank[,-1]

```
<br>

## **Dummy Variables**
```{r}

UniversalBank$Education <- as.factor(UniversalBank$Education)
DummyVariables <- model.matrix(~ Education - 1, data = UniversalBank)
UniversalBank[,colnames(DummyVariables)] <- DummyVariables
UniversalBank <- UniversalBank[,-6]

```
<br>

## **Normalize Data**
```{r}

norm_model <- preProcess(UniversalBank, method = c('range'))
UniversalBank_normalized <- predict(norm_model,UniversalBank)

```
<br>

## **Split Data**
```{r}

set.seed(123)
Index_Train <- createDataPartition(UniversalBank_normalized$`Personal Loan`, p=0.6, list = F)
Train <- UniversalBank_normalized[Index_Train,]
Valid <- UniversalBank_normalized[-Index_Train,]

Train_Predictors <- Train[, colnames(Train) != "Personal Loan"]
Train_labels <- Train$`Personal Loan`
valid_Predictors <- Valid[, colnames(Valid) != "Personal Loan"]
Valid_labels <- Valid$`Personal Loan`

```
<br>

## **Add New Customer**
```{r}

New_Customer <- UniversalBank_normalized[0, ]
New_Customer[1, ] <- data.frame(
  Age = 40,
  Experience = 10,
  Income = 84,
  Family = 2,
  CCAvg = 2,
  Mortgage = 0,
  'Personal Loan' = 0,
  'Securities Account' = 0,
  'CD Account' = 0,
  Online = 1,
  CreditCard = 1,
  Education1 = 0,
  Education2 = 1,
  Education3 = 0
)
New_Customer_norm <- predict(norm_model,New_Customer)
New_Customer_norm <- New_Customer_norm[,-7]
 
```
<br>

## **Run k-NN For New Customer**
```{r}

Predicted_New_Customer <- knn(Train_Predictors,
                             New_Customer_norm,
                             cl=Train_labels,
                             k=1)
print(Predicted_New_Customer)
```
**This new customer would be classified as a failure.**
<br>

## **Find Best K**
```{r}

model <- train(
  `Personal Loan` ~ Age + Experience + Income + Family + CCAvg + Mortgage + 
    `Securities Account` + `CD Account` + Online + CreditCard + Education1 + Education2 + Education3,
  data = UniversalBank,
  method = "knn",
  tuneLength = 10,
  preProcess = 'range'
)
model

```
**The best choice for k is 5.**
<br>

