---
title: "Assignment4"
output: html_document
---

## **Load Libraries**
```{r}

library(readr)
library(factoextra)
library(flexclust)
library(tidyverse)
library(caret)

```
<br>

## **Import Data**
```{r}

Pharmaceuticals <- read_csv("Pharmaceuticals.csv")

```
*Data sourced from Canvas.*

<br>

## **Numerical Variables Only**
```{r}

sapply(Pharmaceuticals, class)
Pharmaceuticals_Num <- Pharmaceuticals[,3:11]
sapply(Pharmaceuticals_Num, class)

```
<br>

## **Normalize Data**
```{r}

set.seed(123)
summary(Pharmaceuticals_Num)
norm_model <- preProcess(Pharmaceuticals_Num, method = c("center", "scale"))
Pharmaceuticals_Norm <- predict(norm_model,Pharmaceuticals_Num)
summary(Pharmaceuticals_Norm)

```
<br>

## **Finding K**
```{r}

fviz_nbclust(Pharmaceuticals_Norm, kmeans, method = "wss")
fviz_nbclust(Pharmaceuticals_Norm, kmeans, method = "silhouette")

```
<br>

## **Clustering**
```{r}

distance <- get_dist(Pharmaceuticals_Norm)
fviz_dist(distance)

Pharmaceuticals_Clusters <- kmeans(Pharmaceuticals_Norm, centers = 4, nstart = 25)
Pharmaceuticals_Clusters$centers
Pharmaceuticals_Clusters$size

fviz_cluster(Pharmaceuticals_Clusters, data = Pharmaceuticals_Norm)

```
<br>


